version: '2'
services:
  mongodb:
    image: mongo:3
  elasticsearch:
    image: elasticsearch:6.8.2
    #volumes:
    #  - /data/elasticsearch:/usr/share/elasticsearch
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 4g
  kibana:
    image: kibana:6.8.2
    #volumes:
    #  - /data/kibana:/usr/share/kibana
    links:
      - elasticsearch
    ports:
      - 5601:5601
  graylog:
    image: graylog/graylog:3.1
    #volumes:
    #  - /data/graylog:/usr/share/graylog
    environment:
      # CHANGE ME (must be at least 16 characters)!
      - GRAYLOG_PASSWORD_SECRET=i2KL7zV2ck0Z4AOe
      # Password: gahw*fchN9m8
      - GRAYLOG_ROOT_PASSWORD_SHA2=f3566a0548cac4bafa4e2f8bafab6850c8856c6bcd0cee372f45221673feaa5d
      - GRAYLOG_HTTP_EXTERNAL_URI=http://10.248.253.70:9000/
      - GRAYLOG_ELASTICSEARCH_HOSTS=http://elasticsearch:9200/
      - GRAYLOG_ROOT_TIMEZONE=Asia/Shanghai
    links:
      - mongodb:mongo
      - elasticsearch
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
